apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-runner-cache-local
  namespace: gitlab-ci
spec:
  storageClassName: manual
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/cache"